sudo: false

addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libiberty-dev

language: bash

cache:
  directories:
  - "${HOME}/google-cloud-sdk/"
  - "${HOME}/kcov/"

env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin:${HOME}/kcov/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- openssl aes-256-cbc -K $encrypted_0ec749be1141_key -iv $encrypted_0ec749be1141_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d "${HOME}/google-cloud-sdk/bin" ]; then rm -rf ${HOME}/google-cloud-sdk;
  curl https://sdk.cloud.google.com | bash; fi
- tar -xzf credentials.tar.gz
- gcloud auth activate-service-account --key-file client-secret.json
- if [ ! -d "${HOME}/kcov/bin" ]; then wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz;
  tar xzf master.tar.gz;
  cd kcov-master;
  mkdir build;
  cd build;
  cmake -DCMAKE_INSTALL_PREFIX=${HOME}/kcov ..;
  make;
  make install;
  cd ../..;
  rm -rf kcov-master;
  mkdir -p coverage; fi

install:
- gcloud -q components update
- gcloud -q components install kubectl

script:
- kcov --exclude-path=ops-common coverage test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  slack: lzysh:0nheJvFHhsWdYlVVfdX0mRNu