sudo: false
language: bash
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
env:
- PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
- openssl aes-256-cbc -K $encrypted_0ec749be1141_key -iv $encrypted_0ec749be1141_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- if [ ! -d "${HOME}/google-cloud-sdk/bin" ]; then rm -rf ${HOME}/google-cloud-sdk;
  curl https://sdk.cloud.google.com | bash; fi
- tar -xzf credentials.tar.gz
- gcloud auth activate-service-account --key-file client-secret.json
install:
- gcloud -q components update
- gcloud -q components install kubectl
script:
- "./test.sh"
notifications:
  slack: lzysh:0nheJvFHhsWdYlVVfdX0mRNu
