coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        only_pulls: false
        branches: null
        flags: null
        paths: null