apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.141
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: JENKINS_OPTS
          value: --argumentsRealm.passwd.jenkins=t3mp123 --argumentsRealm.roles.jenkins=admin
        - name: JAVA_OPTS
          value: -Duser.timezone=America/New_York -Dhudson.model.DirectoryBrowserSupport.CSP="sandbox allow-same-origin allow-scripts; default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; script-src 'self' 'unsafe-inline'; font-src 'self'"
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          initialDelaySeconds: 15
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
      volumes:
      - name: jenkins-home
        gcePersistentDisk:
          pdName: jenkins-home
          fsType: ext4
          partition: 1
